import { Inter } from 'next/font/google'
import { Theme } from "@radix-ui/themes"
import './theme-config.css';
import '@radix-ui/themes/styles.css';
import './globals.css'
import type { Metadata } from 'next'
import { NextAuthProvider } from './providers'
const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.variable}>
        <Theme>
          <NextAuthProvider>
            {children}
          </NextAuthProvider>
        </Theme>
      </body>
    </html>
  )
}
